package com.lock4.finalapp
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.provider.Settings;import android.widget.*
class MainActivity:Activity(){private val p by lazy{getSharedPreferences("lock4",0)};private var timer:CountDownTimer?=null;private lateinit var status:TextView;private lateinit var remain:TextView
private val apps=listOf("com.instagram.android" to "Instagram","com.google.android.youtube" to "YouTube","com.google.android.apps.youtube.music" to "YouTube Music","com.facebook.katana" to "Facebook","com.snapchat.android" to "Snapchat")
private fun tv(s:String,z:Float)=TextView(this).apply{text=s;textSize=z;setTextColor(Color.WHITE);setPadding(0,10,0,10)}
override fun onCreate(b:Bundle?){super.onCreate(b);val r=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(28,32,28,28);setBackgroundColor(Color.rgb(9,11,14))};r.addView(tv("LOCK//4",30f));r.addView(tv("FINAL • 120-DAY STUDY LOCK-IN",12f));status=tv("READY",22f);remain=tv("No active session",14f);r.addView(status);r.addView(remain);r.addView(tv("BLOCKED APPS",11f));apps.forEach{(pkg,n)->r.addView(CheckBox(this).apply{text=n;setTextColor(Color.WHITE);isChecked=p.getBoolean("blocked_$pkg",n=="Instagram"||n=="YouTube");setOnCheckedChangeListener{_,v->p.edit().putBoolean("blocked_$pkg",v).apply()}})};r.addView(Button(this).apply{text="START 50-MIN LOCK-IN";setOnClickListener{start(50)}});r.addView(Button(this).apply{text="START CUSTOM SESSION";setOnClickListener{val e=EditText(this@MainActivity);e.hint="Minutes";e.inputType=2;AlertDialog.Builder(this@MainActivity).setTitle("Session length").setView(e).setPositiveButton("START"){_,_->e.text.toString().toIntOrNull()?.let{start(it)}}.setNegativeButton("CANCEL",null).show()}});r.addView(Button(this).apply{text="END LOCK-IN";setOnClickListener{end()}});r.addView(Button(this).apply{text="ENABLE / CHECK BLOCKER PERMISSION";setOnClickListener{startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))}});r.addView(tv("During Lock-In, selected apps are blocked. Android requires you to explicitly enable Accessibility permission. Use END LOCK-IN as the emergency exit.",11f));setContentView(r);restore()}
private fun start(m:Int){if(m<1)return;LockState.endAt=System.currentTimeMillis()+m*60000L;LockState.enabled=true;p.edit().putLong("endAt",LockState.endAt).apply();runTimer()}
private fun restore(){val e=p.getLong("endAt",0);if(e>System.currentTimeMillis()){LockState.endAt=e;LockState.enabled=true;runTimer()}else end()}
private fun runTimer(){timer?.cancel();status.text="FOCUS ACTIVE";timer=object:CountDownTimer(LockState.endAt-System.currentTimeMillis(),1000){override fun onTick(x:Long){remain.text="Remaining: ${x/60000}m ${(x/1000)%60}s"};override fun onFinish(){end()}}.start()}
private fun end(){timer?.cancel();LockState.enabled=false;LockState.endAt=0;p.edit().remove("endAt").apply();if(::status.isInitialized){status.text="READY";remain.text="Session ended"}}}
object LockState{@Volatile var enabled=false;@Volatile var endAt=0L}
